export const messagesCode: { [code: string]: string } = {
    "00000": "Acción realizada exitosamente",
    ERD00: "UNEXPECTED DATABASE DOCUMENT ERROR",
    ERD01: "El documento ya existe",
    ERR00: "UNEXPECTED INTERNAL ERROR",
    ERR01: "El nombre de usuario tiene un formato incorrecto",
    ERR02: "El correo del usuario tiene un formato incorrecto, debe ser del formato: correo@correo.cl",
    ERR03: "La contraseña del usuario tiene un formato incorrecto, debe ser alfanumérica",
    ERR04: "Las contraseñas no son iguales",
    ERR05: "Código incorrecto",
    ERR09: "Faltan datos requeridos ",
    ERL01: "El usuario no existe",
    ERL02: "La cuenta está bloqueada, contacte con soporte",
    ERL03: "Contraseña incorrecta",
};
